# wrangler.toml
name = "my-next-on-pages-site"         # optional for Pages, harmless if present
compatibility_date = "2025-06-28"      # must be ≥ 2024-09-23
compatibility_flags = ["nodejs_compat"]

# If you want different settings per env:
[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]
