packages:
  - apps/*
  - packages/*

catalog:
  typescript: 5.7.3
  react: 19.1.0
  react-dom: 19.1.0
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@types/node': 20.3.1
  lucide-react: 0.517.0

ignoredBuiltDependencies:
  - '@clerk/shared'

onlyBuiltDependencies:
  - '@nestjs/core'
  - core-js-pure
  - sharp
